### ISSUE TITLE
My entire file navigator is blank now

### ISSUE THREAD

**Issue by luckman212** [JonasDoesThings/obsidian-hide-folders#1]
- macOS 13.5
- Obsidian 1.4.1 
- obsidian-hide-folders 1.0.2

When I enable this plugin, my entire File Navigator pane becomes empty/blank. I don't see any JS errors in the console. At first I thought it might be because I have `( )`s in one of my ignored folder names: `templates (disabled)` but I removed that and just left `attach` as the single entry, and it's still blank.

**Comment by JonasDoesThings** [comment]
Hi, thanks for reporting. :) 

I don't have access to the Obsidian preview version 1.4.1 so I cannot test if the version is a problem. If you have the old stable version (1.3.5) installed too, you could check if the issue persists.

Besides that, do you have any plugin(s) installed that modify the file navigator UI? Maybe there's some interference caused by that.

**Comment by luckman212** [comment]
Thanks! Indeed, the new version is working fine now! 🚀

**Comment by JonasDoesThings** [comment]
Wow, quick response! :D 
Happy that it works now, feel free to report back any further issues or suggestions :)
