### ISSUE TITLE
Folders are unhidden after restarting the app

### ISSUE THREAD

**Issue by ivensrocha** [JonasDoesThings/obsidian-hide-folders#8]
Hi,

First of all, thanks for your plugin!

I have encountered a situation when folders are hidden and when I restart Obsidian, the files are unhidden again. Is this an expected behavior? If yes, why? If not, is there a plan to fix it?

Thank you!

**Comment by JonasDoesThings** [comment]
Hi @ivensrocha , you are right - turns out the current implementation does not call the save settings function after updating the hidden-folder setting via the side-bar button or action. 

This is **not** on purpose, and I will release a version that fixes this issue later today :)

Thanks for reporting!

**Comment by JonasDoesThings** [comment]
Fixed in v1.2.3
Thanks for reporting :)

Feel free to reopen / open another issue if you have more issues.
Greetings from Austria
